{
"order_id":"138",
"tracking_id":"309006142113",
"bank_ref_no":"700202017663254742",
"order_status":"Failure",
"failure_message":"",
"payment_mode":"Credit Card",
"card_name":"Visa",
"status_code":"null",
"status_message":"Transaction Declined by Bank(Not Enrolled Card)",
"currency":"INR",
"amount":"499.00",
"billing_name":"",
"billing_address":"Kerala",
"billing_city":"",
"billing_state":"",
"billing_zip":"673014",
"billing_country":"",
"billing_tel":"",
"billing_email":"",
"delivery_name":"Anju",
"delivery_address":"calicut",
"delivery_city":"Calicut",
"delivery_state":"Kerala",
"delivery_zip":"673305",
"delivery_country":"India",
"delivery_tel":"7865456789",
"merchant_param1":"",
"merchant_param2":"",
"merchant_param3":"",
"merchant_param4":"",
"merchant_param5":"",
"vault":"N",
"offer_type":"null",
"offer_code":"null",
"discount_value":"0.0",
"mer_amount":"499.00",
"eci_value":"1",
"retry":"N",
"response_code":"0",
"billing_notes":"",
"trans_date":"24\/06\/2020 10:07:10",
"bin_country":"UNITED STATES"
}
